// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO. 
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.refactoring.rxo.entity.account;


import com.baomidou.mybatisplus.annotations.TableField;
import com.refactoring.rxo.datasource.mybatis.BaseEntity;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.springframework.util.CollectionUtils;

import java.util.ArrayList;
import java.util.List;

/**
 */
public class Resource extends BaseEntity<Resource> {

	public static final String TOP_NODE_ID = "-1";
    
    private Integer version;
    
    private String name;
    
    
    private Integer orderIndex;
    
    private String url;
    
    
    private String parentId;

    private String type;
    
    private String code;

	private String function;

	@TableField(exist = false)
	private List<Resource> children;
    
    
    /**
     * Method getName.
     * @return String
     */
    public String getName(){
		return name;
	}
	/**
	 * Method setName.
	 * @param name String
	 */
	public void setName(String name) {
		this.name = name;
	}
    
    /**
     * Method getOrderIndex.
     * @return Integer
     */
    public Integer getOrderIndex(){
		return orderIndex;
	}
	/**
	 * Method setOrderIndex.
	 * @param orderIndex Integer
	 */
	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}
    
    /**
     * Method getUrl.
     * @return String
     */
    public String getUrl(){
		return url;
	}
	/**
	 * Method setUrl.
	 * @param url String
	 */
	public void setUrl(String url) {
		this.url = url;
	}
    
    /**
     * Method getParentId.
     * @return Integer
     */
    public String getParentId(){
		return parentId;
	}
	/**
	 * Method setParentId.
	 * @param parentId Integer
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}
    
    /**
     * Method getType.
     * @return String
     */
    public String getType(){
		return type;
	}
	/**
	 * Method setType.
	 * @param type String
	 */
	public void setType(String type) {
		this.type = type;
	}
    
    
	/**
	
	 * @return the version */
	public Integer getVersion() {
		return version;
	}

	/**
	 * @param version the version to set
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getFunction() {
		return function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}

	public List<Resource> getChildren() {
		return children;
	}

	public void setChildren(List<Resource> children) {
		this.children = children;
	}

	public void addChild(Resource resource){
		if(CollectionUtils.isEmpty(children)){
			children = new ArrayList<>();
		}
		children.add(resource);
	}

	/**
	 * Method toString.
	 * @return String
	 */
	@Override
	public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
	
    
}
